// Auto-generated homepage data
// Generated on: 2026-01-04T09:09:52.816Z
// DO NOT EDIT THIS FILE DIRECTLY - Run 'npm run export-homepage' to regenerate

// Editor's Pick - Curated quality stories
export const EDITOR_PICKS = [
  {
    "id": "694f890a920aaf27bfc71dc2",
    "title": "When the Wind Forgets to Blow",
    "author": "Starlit Journals",
    "coverImage": "https://i.ibb.co/PZpcVYzS/story-1767286033328.webp",
    "genres": [
      "Romance"
    ],
    "readTime": 10
  },
  {
    "id": "693ec8b5945dc639e08f963c",
    "title": "The Lactation Ward",
    "author": "Forgotten Ritual",
    "coverImage": "https://i.ibb.co/xtKNL19b/dde9c236b80c.webp",
    "genres": [
      "Horror",
      "Thriller"
    ],
    "readTime": 14
  },
  {
    "id": "693e492b054ee2f9aebd361f",
    "title": "A small tax on Miracles",
    "author": "Dharma",
    "coverImage": "https://i.ibb.co/Kx3yDZYt/2729fd4e094a.webp",
    "genres": [
      "Drama",
      "Slice of Life"
    ],
    "readTime": 13
  },
  {
    "id": "693d1d0459f1aec7e54942ff",
    "title": "Before the First Lie Was Told",
    "author": "Dharma",
    "coverImage": "https://i.ibb.co/XZM6mwB7/5018bb70226e.webp",
    "genres": [
      "Fantasy",
      "Drama"
    ],
    "readTime": 11
  },
  {
    "id": "69355933cdab065d273496e5",
    "title": "The Boy Who Carried the Sun Through Winter",
    "author": "Aarin Hale",
    "coverImage": "https://i.ibb.co/wFzqLrpH/ae41352d79e2.webp",
    "genres": [
      "Fantasy"
    ],
    "readTime": 13
  }
];

// Quick Reads - Stories under 5 minutes
export const QUICK_READS = [
  {
    "id": "695a2223eab2d19a346fd4c9",
    "title": "A Pair of Silk Stockings",
    "author": "SliceOfLife Archives",
    "coverImage": "https://pub-4a701d352c1f488cbbf56c773984ae36.r2.dev/1767514621317-story_1767514621317.webp",
    "genres": [
      "Slice of Life",
      "Drama"
    ],
    "readTime": 8
  },
  {
    "id": "695a1f79eab2d19a346fd4bc",
    "title": "The Gift of the Magi",
    "author": "SliceOfLife Archives",
    "coverImage": "https://pub-4a701d352c1f488cbbf56c773984ae36.r2.dev/1767513953325-story_1767513953325.webp",
    "genres": [
      "Slice of Life",
      "Drama"
    ],
    "readTime": 8
  },
  {
    "id": "6958e4fe707a4b86531fefb3",
    "title": "The Story of an Hour",
    "author": "Drama Archives",
    "coverImage": "https://pub-4a701d352c1f488cbbf56c773984ae36.r2.dev/1767505615238-story_1767505615238.webp",
    "genres": [
      "Drama"
    ],
    "readTime": 4
  },
  {
    "id": "69563cc65c6234987addd17c",
    "title": "The Boarded Window",
    "author": "Thriller Archives",
    "coverImage": "https://i.ibb.co/bgr5k12Q/story-1767268301992.webp",
    "genres": [
      "Thriller"
    ],
    "readTime": 7
  },
  {
    "id": "69562f18fe6280eaf4de0034",
    "title": "The Open Window",
    "author": "The Public Horrors",
    "coverImage": "https://i.ibb.co/LwbPjGb/story-1767255790250.webp",
    "genres": [
      "Thriller"
    ],
    "readTime": 5
  },
  {
    "id": "69562879fe6280eaf4de001e",
    "title": "The Cask of Amontillado (ReWritten)",
    "author": "The Public Horrors",
    "coverImage": "https://i.ibb.co/bVVfbpP/story-1767268508012.webp",
    "genres": [
      "Horror",
      "Thriller"
    ],
    "readTime": 8
  }
];

// Genre-specific sections
export const FANTASY_STORIES = [
  // {
  //   "id": "694eb8e73a748d888079b5da",
  //   "title": "Vincent",
  //   "author": "Aaron David",
  //   "coverImage": "https://i.ibb.co/1JX3yTNt/0fddb8bd08cc.webp",
  //   "genres": [
  //     "Fantasy"
  //   ],
  //   "readTime": 13
  // },
  {
    "id": "69355933cdab065d273496e5",
    "title": "The Boy Who Carried the Sun Through Winter",
    "author": "Aarin Hale",
    "coverImage": "https://i.ibb.co/wFzqLrpH/ae41352d79e2.webp",
    "genres": [
      "Fantasy"
    ],
    "readTime": 13
  },
  // {
  //   "id": "694ab29d585c27903a41490d",
  //   "title": "Murder & Robbery",
  //   "author": "Tom Kropp",
  //   "coverImage": "https://i.ibb.co/QFt0xh2m/5d1cdbb1c80e.webp",
  //   "genres": [
  //     "Fantasy",
  //     "Thriller",
  //     "Horror"
  //   ],
  //   "readTime": 14
  // },
  {
    "id": "694581540f3e2033412a91e4",
    "title": "What He Fixed by Breaking",
    "author": "Aarin Hale",
    "coverImage": "https://i.ibb.co/cKgxmM8B/What-He-Fixed-by-Breaking.webp",
    "genres": [
      "Fantasy",
      "Slice of Life",
      "Drama"
    ],
    "readTime": 7
  },
  {
    "id": "693d1d0459f1aec7e54942ff",
    "title": "Before the First Lie Was Told",
    "author": "Dharma",
    "coverImage": "https://i.ibb.co/XZM6mwB7/5018bb70226e.webp",
    "genres": [
      "Fantasy",
      "Drama"
    ],
    "readTime": 11
  },
  // {
  //   "id": "694b47cb925b6945aebc087b",
  //   "title": "Astral Homicidal Hunter",
  //   "author": "Tom Kropp",
  //   "coverImage": "https://i.ibb.co/fGnb1Wcg/Astral-Homicidal-Hunter.webp",
  //   "genres": [
  //     "Thriller",
  //     "Horror",
  //     "Fantasy"
  //   ],
  //   "readTime": 15
  // },
  {
    "id": "693c1ba2d837caf4fc701968",
    "title": "What stayed after my CATS left",
    "author": "Dharma",
    "coverImage": "https://i.ibb.co/wh8Sdvqc/What-stayed-after-my-CATS-left.webp",
    "genres": [
      "Slice of Life",
      "Fantasy"
    ],
    "readTime": 14
  }
];

export const DRAMA_STORIES = [
  {
    "id": "695a12291abeede64ce6b440",
    "title": "God Sees the Truth, But Waits",
    "author": "Drama Archives",
    "coverImage": "https://pub-4a701d352c1f488cbbf56c773984ae36.r2.dev/1767510541293-story_1767510541292.webp",
    "genres": [
      "Drama"
    ],
    "readTime": 12
  },
  {
    "id": "695a104f1abeede64ce6b433",
    "title": "The Necklace",
    "author": "Drama Archives",
    "coverImage": "https://pub-4a701d352c1f488cbbf56c773984ae36.r2.dev/1767510068628-story_1767510068627.webp",
    "genres": [
      "Drama"
    ],
    "readTime": 11
  },
  {
    "id": "6959ffa51abeede64ce6b41a",
    "title": "The Bet",
    "author": "Drama Archives",
    "coverImage": "https://pub-4a701d352c1f488cbbf56c773984ae36.r2.dev/1767505797799-story_1767505797799.webp",
    "genres": [
      "Drama"
    ],
    "readTime": 11
  },
  
  {
    "id": "693e492b054ee2f9aebd361f",
    "title": "A small tax on Miracles",
    "author": "Dharma",
    "coverImage": "https://i.ibb.co/Kx3yDZYt/2729fd4e094a.webp",
    "genres": [
      "Drama",
      "Slice of Life"
    ],
    "readTime": 13
  },
  {
    "id": "69358203cdab065d27349aa9",
    "title": "My Mother Is Falling in Love With the Man She Could Have Married",
    "author": "Mira Soren",
    "coverImage": "https://i.ibb.co/r2nRp3JS/bdec679313d4.webp",
    "genres": [
      "Drama",
      "Slice of Life"
    ],
    "readTime": 9
  },
  {
    "id": "695a27a7eab2d19a346fd4d9",
    "title": "A Little Cloud",
    "author": "SliceOfLife Archives",
    "coverImage": "https://pub-4a701d352c1f488cbbf56c773984ae36.r2.dev/1767516041883-story_1767516041883.webp",
    "genres": [
      "Slice of Life",
      "Drama"
    ],
    "readTime": 15
  },
];

export const ROMANCE_STORIES = [
  {
    "id": "694f890a920aaf27bfc71dc2",
    "title": "When the Wind Forgets to Blow",
    "author": "Starlit Journals",
    "coverImage": "https://i.ibb.co/PZpcVYzS/story-1767286033328.webp",
    "genres": [
      "Romance"
    ],
    "readTime": 10
  },
  {
    "id": "694f8a11613baf95f13bab46",
    "title": "Velvet in the Rain",
    "author": "Starlit Journals",
    "coverImage": "https://i.ibb.co/N6wmmVvt/story-1767286352180.webp",
    "genres": [
      "Romance",
      "Slice of Life"
    ],
    "readTime": 8
  },
  {
    "id": "694f925c08856d8428f5e263",
    "title": "Don’t Date Your Doomsday Cult Leader",
    "author": "SravYeah!",
    "coverImage": "https://i.ibb.co/svT83VmC/story-1767285872297.webp",
    "genres": [
      "Comedy",
      "Romance"
    ],
    "readTime": 8
  }
];

export const SLICE_OF_LIFE_STORIES = [
  {
    "id": "693c1ba2d837caf4fc701968",
    "title": "What stayed after my CATS left",
    "author": "Dharma",
    "coverImage": "https://i.ibb.co/wh8Sdvqc/What-stayed-after-my-CATS-left.webp",
    "genres": [
      "Slice of Life",
      "Fantasy"
    ],
    "readTime": 14
  },
  {
    "id": "695a27a7eab2d19a346fd4d9",
    "title": "A Little Cloud",
    "author": "SliceOfLife Archives",
    "coverImage": "https://pub-4a701d352c1f488cbbf56c773984ae36.r2.dev/1767516041883-story_1767516041883.webp",
    "genres": [
      "Slice of Life",
      "Drama"
    ],
    "readTime": 15
  },
  {
    "id": "695a2223eab2d19a346fd4c9",
    "title": "A Pair of Silk Stockings",
    "author": "SliceOfLife Archives",
    "coverImage": "https://pub-4a701d352c1f488cbbf56c773984ae36.r2.dev/1767514621317-story_1767514621317.webp",
    "genres": [
      "Slice of Life",
      "Drama"
    ],
    "readTime": 8
  },
  {
    "id": "695a1f79eab2d19a346fd4bc",
    "title": "The Gift of the Magi",
    "author": "SliceOfLife Archives",
    "coverImage": "https://pub-4a701d352c1f488cbbf56c773984ae36.r2.dev/1767513953325-story_1767513953325.webp",
    "genres": [
      "Slice of Life",
      "Drama"
    ],
    "readTime": 8
  },
  {
    "id": "694f92f1a2782b47f4123f7f",
    "title": "Flatmates from Planet 9",
    "author": "SravYeah!",
    "coverImage": "https://i.ibb.co/rfft3G0V/story-1767285656409.webp",
    "genres": [
      "Comedy",
      "Slice of Life"
    ],
    "readTime": 7
  },
  {
    "id": "695a65964f5bb03aec28a10d",
    "title": "The Darling",
    "author": "SliceOfLife Archives",
    "coverImage": "https://pub-4a701d352c1f488cbbf56c773984ae36.r2.dev/1767531886259-story_1767531886259.webp",
    "genres": [
      "Slice of Life",
    "Drama",
    "Romance"
    ],
    "readTime": 13
  },
];

export const THRILLER_STORIES = [
  {
    "id": "69563cc65c6234987addd17c",
    "title": "The Boarded Window",
    "author": "Thriller Archives",
    "coverImage": "https://i.ibb.co/bgr5k12Q/story-1767268301992.webp",
    "genres": [
      "Thriller"
    ],
    "readTime": 7
  },
  {
    "id": "69563b395c6234987addd15a",
    "title": "An Occurrence at Owl Creek Bridge",
    "author": "Thriller Archives",
    "coverImage": "https://i.ibb.co/Wv0ZPpJb/story-1767268216409.webp",
    "genres": [
      "Thriller"
    ],
    "readTime": 14
  },
  {
    "id": "69562f18fe6280eaf4de0034",
    "title": "The Open Window",
    "author": "The Public Horrors",
    "coverImage": "https://i.ibb.co/LwbPjGb/story-1767255790250.webp",
    "genres": [
      "Thriller"
    ],
    "readTime": 5
  },
  {
    "id": "694b47cb925b6945aebc087b",
    "title": "Astral Homicidal Hunter",
    "author": "Tom Kropp",
    "coverImage": "https://i.ibb.co/fGnb1Wcg/Astral-Homicidal-Hunter.webp",
    "genres": [
      "Thriller",
      "Horror",
      "Fantasy"
    ],
    "readTime": 15
  },
  {
    "id": "69562879fe6280eaf4de001e",
    "title": "The Cask of Amontillado (ReWritten)",
    "author": "The Public Horrors",
    "coverImage": "https://i.ibb.co/bVVfbpP/story-1767268508012.webp",
    "genres": [
      "Horror",
      "Thriller"
    ],
    "readTime": 8
  },
  {
    "id": "695623deab3b7bb9388f4beb",
    "title": "The Tell-Tale Heart",
    "author": "The Public Horrors",
    "coverImage": "https://i.ibb.co/S1Nfkgn/story-1767268414951.webp",
    "genres": [
      "Horror",
      "Thriller"
    ],
    "readTime": 9
  },
  {
    "id": "694ab29d585c27903a41490d",
    "title": "Murder & Robbery",
    "author": "Tom Kropp",
    "coverImage": "https://i.ibb.co/QFt0xh2m/5d1cdbb1c80e.webp",
    "genres": [
      "Fantasy",
      "Thriller",
      "Horror"
    ],
    "readTime": 14
  },
  {
    "id": "694566813a34a78e49e3e482",
    "title": "The Proxy Daughters",
    "author": "Forgotten Ritual",
    "coverImage": "https://i.ibb.co/MLXjjy1/The-Proxy-Daughters.webp",
    "genres": [
      "Horror",
      "Thriller"
    ],
    "readTime": 11
  },
  {
    "id": "6943d187279d8260bf46808b",
    "title": "The Skin Telephone",
    "author": "Forgotten Ritual",
    "coverImage": "https://i.ibb.co/gbWHXjSZ/6ba4e0834767.webp",
    "genres": [
      "Horror",
      "Thriller"
    ],
    "readTime": 8
  },
  {
    "id": "693ec8b5945dc639e08f963c",
    "title": "The Lactation Ward",
    "author": "Forgotten Ritual",
    "coverImage": "https://i.ibb.co/xtKNL19b/dde9c236b80c.webp",
    "genres": [
      "Horror",
      "Thriller"
    ],
    "readTime": 14
  }
];

export const HORROR_STORIES = [
  
  {
    "id": "69562879fe6280eaf4de001e",
    "title": "The Cask of Amontillado (ReWritten)",
    "author": "The Public Horrors",
    "coverImage": "https://i.ibb.co/bVVfbpP/story-1767268508012.webp",
    "genres": [
      "Horror",
      "Thriller"
    ],
    "readTime": 8
  },
  {
    "id": "695623deab3b7bb9388f4beb",
    "title": "The Tell-Tale Heart",
    "author": "The Public Horrors",
    "coverImage": "https://i.ibb.co/S1Nfkgn/story-1767268414951.webp",
    "genres": [
      "Horror",
      "Thriller"
    ],
    "readTime": 9
  },
  {
    "id": "694566813a34a78e49e3e482",
    "title": "The Proxy Daughters",
    "author": "Forgotten Ritual",
    "coverImage": "https://i.ibb.co/MLXjjy1/The-Proxy-Daughters.webp",
    "genres": [
      "Horror",
      "Thriller"
    ],
    "readTime": 11
  },
  {
    "id": "6943d187279d8260bf46808b",
    "title": "The Skin Telephone",
    "author": "Forgotten Ritual",
    "coverImage": "https://i.ibb.co/gbWHXjSZ/6ba4e0834767.webp",
    "genres": [
      "Horror",
      "Thriller"
    ],
    "readTime": 8
  },
  {
    "id": "693ec8b5945dc639e08f963c",
    "title": "The Lactation Ward",
    "author": "Forgotten Ritual",
    "coverImage": "https://i.ibb.co/xtKNL19b/dde9c236b80c.webp",
    "genres": [
      "Horror",
      "Thriller"
    ],
    "readTime": 14
  },
  {
    "id": "69562b0afe6280eaf4de002a",
    "title": "The Monkey's PAW",
    "author": "The Public Horrors",
    "coverImage": "https://i.ibb.co/8Lm3PMqt/story-1767254751858.webp",
    "genres": [
      "Horror"
    ],
    "readTime": 15
  },
];

export const COMEDY_STORIES = [
 
  {
    "id": "69565e64cfea22882082fa46",
    "title": "The Ransom of Red Chief",
    "author": "Comedy Archives",
    "coverImage": "https://i.ibb.co/JRtmjrPW/story-1767267913583.webp",
    "genres": [
      "Comedy"
    ],
    "readTime": 13
  },
  {
    "id": "6950042982ce69385b754c76",
    "title": "The Ghost in My Group Chat",
    "author": "SravYeah!",
    "coverImage": "https://i.ibb.co/nNfwG2ML/story-1767285275210.webp",
    "genres": [
      "Comedy",
      "Horror"
    ],
    "readTime": 7
  },
  {
    "id": "694f92f1a2782b47f4123f7f",
    "title": "Flatmates from Planet 9",
    "author": "SravYeah!",
    "coverImage": "https://i.ibb.co/rfft3G0V/story-1767285656409.webp",
    "genres": [
      "Comedy",
      "Slice of Life"
    ],
    "readTime": 7
  },
  {
    "id": "694f925c08856d8428f5e263",
    "title": "Don’t Date Your Doomsday Cult Leader",
    "author": "SravYeah!",
    "coverImage": "https://i.ibb.co/svT83VmC/story-1767285872297.webp",
    "genres": [
      "Comedy",
      "Romance"
    ],
    "readTime": 8
  },
  {
    "id": "69569de6b66cf2e1efee63d1",
    "title": "The Celebrated Jumping Frog of Calaveras County",
    "author": "Comedy Archives",
    "coverImage": "https://i.ibb.co/bM0h9Wh1/story-1767284116853.webp",
    "genres": [
      "Comedy"
    ],
    "readTime": 11
  },
];
